[supervisord]
nodaemon=true

[program:mysql]
command=/bin/bash -c "service mariadb start && sleep 3 && mysql < /init.sql && tail -f /var/log/mysql/error.log"
autorestart=true

[program:apache]
command=apache2-foreground
autorestart=true